name: hexlet-ci
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: clone rep
        uses: actions/checkout@v2
      - name: install node => 12 and <=16
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
          cache: 'npm'
      - name: setup
        run: make setup
      - name: snyk start
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name : start test
        run: make test
      - name: start eslint
        run: make lint



